server:
  port: 8081

spring:
    datasource:
        name: db1
        url: jdbc:mysql://192.168.1.218:3306/crm
        username: root
        password: da123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
         max-active: 20
         initial-size: 20
         min-idle: 1
         max-wait: 60000
         time-between-eviction-runs-millis: 60000
         min-evictable-idle-time-millis: 300000
         validation-query: select 'x'
         test-while-idle: true
         test-on-borrow: false
         test-on-return: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mi.entity
 
#pagehelper分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-dialect: mysql

imagePath: E:\
filePath: E:\
